sheduler:
  serviceAccountName: postgres-scheduler-sa
  image: "oilerbackup/postgres-scheduler:0.0.1"
  imagePullPolicy: Always
  name: postgres-scheduler
  namespace: oiler-backup-system
  port: 50051
  replicas: 1
backuper:
  image: "oilerbackup/postgres-backuper:0.0.1"
restorer:
  image: "oilerbackup/postgres-restorer:0.0.1"