sheduler:
  serviceAccountName: postgres-scheduler-sa
  image: "sveb00/pgad:0.0.1-2"
  imagePullPolicy: Always
  name: postgres-scheduler
  namespace: oiler-backup-system
  port: 50051
  replicas: 1
backuper:
  image: "ashadrinnn/pgbackuper:0.0.1-0"
restorer:
  image: "sveb00/pgrestorer:0.0.1-1"