apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sheduler.name }}-service
  namespace: {{ .Values.sheduler.namespace }}
spec:
  selector:
    app: {{ .Values.sheduler.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.sheduler.port | default "50051" }}
      targetPort: {{ .Values.sheduler.port | default "50051" }}
  type: ClusterIP